Helper function to read h5ad file from google bucket
cellarium-ai/scvi-distributed pull request #2
Opened 2023-01-24 17:33 UTC by ordabayevy

2023-01-24 20:50 UTC, mbabadi requested changes

2023-01-24 20:50 UTC, mbabadi commented on scvid/data/read.py
> +    storage_client = storage.Client()
Consider the following change:

```
from google.cloud.storage import Client

def read_h5ad_gcs(filename: str, storage_client: Optional[Client]):
    ...
    if storage_clientis None:
        storage_client= Client()
    ... 
```

We will soon find use-cases where the GCS storage client needs to be authenticated with privileged API tokens.

2023-01-24 20:50 UTC, mbabadi commented on scvid/data/read.py
> +def read_h5ad_filename(filename: str) -> AnnData:
Consider further refactoring to `read_h5ad_local` and `read_h5ad` which handles mixed input.

2023-01-24 23:33 UTC, ordabayevy commented
@mbabadi does it look good now?

2023-01-25 00:37 UTC, mbabadi commented
@ordabayevy Almost :) The reason I suggested declaring the kwarg `storage_client` as `Optional[Client] = None`  was due to python's eagerness to evaluate all expressions, and that includes kwarg default values. Making a habit of declaring _expensive_ kwarg default values (such as `Client()`) is one reason some python package are slow to import. I personally avoid this pattern, but that's entirely up to you.

2023-01-25 01:30 UTC, ordabayevy commented
@mbabadi interesting, good to know! Actually glad I wrote it that way first so now I know more about Python :)

2023-01-25 15:00 UTC, mbabadi approved these changes

2023-01-25 15:07 UTC, merged