Distributed AnnCollection
cellarium-ai/scvi-distributed pull request #4
Opened 2023-01-30 01:35 UTC by ordabayevy

2023-01-31 19:04 UTC, mbabadi requested changes
Back to you @ordabayevy :)

2023-01-31 19:04 UTC, mbabadi commented on test/test_distributed_anndata.py
> +    np.testing.assert_array_equal(dat_view.obs["A"], dat_view.obs["A"])
Additional tests:
- different max cache sizes (1, 2, 3)
- failure in strict mode if __get_item__ indices span too many chunks
- success in non-strict mode if __get_item__ indices span too many chunks
- explicit asserts that no more than maxsize chunks are in the LRU cache
- additional gene-level slicing than `, :2]` in all tests

2023-02-02 00:18 UTC, ordabayevy commented
Back to you @mbabadi :) Address all the comments.

2023-02-02 00:23 UTC, ordabayevy commented
Removed `expand_urls` altogether since we only need simple `braceexpand`. There might be inefficiencies in `_normalize_indices` and `_resolve_idx` when the number of files is too big but I decided to address it in another issue or PR.

2023-02-02 00:46 UTC, mbabadi commented
@ordabayevy great! please make an issue about potential inefficiencies in `_normalize_indices` and `_resolve_idx` and feel free to merge!

2023-02-02 00:46 UTC, mbabadi approved these changes

2023-02-02 00:58 UTC, merged

2023-02-02 00:58 UTC, ordabayevy commented
Thanks for reviewing @mbabadi !