Refactor `module`
cellarium-ai/scvi-distributed pull request #54
Opened 2023-05-03 22:35 UTC by ordabayevy

- Combine `PyroTrainingPlan` and `DummyTrainingPlan`
- Rename `ProbabilisticPCAPyroModule` to `ProbabilisticPCA`
- Add `forward` method to the `ProbabilisticPCA`
- Use `register_buffer` for `torch.nn.Module` attributes so that they are saved at checkpointing
- Fix type hints for `mean_g`, `optim_fn`, `scheduler_fn`
- Add shape hints for `OnePassMeanVarStd` attributes (e.g. `mean` -> `mean_g`)

2023-06-21 00:57 UTC, mbabadi requested changes
Nicely done!

2023-06-21 00:57 UTC, mbabadi commented on scvid/train/training_plan.py
>              optim_kwargs["lr"] = 1e-3
Magic number in the middle of a method-- move it to the initializer kwargs with a default or a _consts.py.

2023-06-21 05:56 UTC, ordabayevy commented
@mbabadi thanks! Added `default_lr` kwarg and fixed some mypy errors.

2023-06-23 14:55 UTC, mbabadi approved these changes

2023-06-23 14:56 UTC, merged