DistributedPCA
cellarium-ai/scvi-distributed pull request #63
Opened 2023-07-03 09:48 UTC by ordabayevy

2023-07-05 15:00 UTC, ordabayevy commented
Blocked by #61

2023-07-10 20:52 UTC, mbabadi requested changes

2023-07-10 20:52 UTC, mbabadi commented on scvid/callbacks/distributed_pca.py
> +    Distributed PCA.
Please write a good amount of documentation about the logic, because it is beautiful! :)

2023-07-10 20:52 UTC, mbabadi commented on scvid/callbacks/distributed_pca.py
> +                    A = torch.diag(S_k) @ V_kg
use `einsum`?

2023-07-10 20:52 UTC, mbabadi commented on scvid/callbacks/distributed_pca.py
> +                    A = torch.diag(S_k) @ V_kg
maybe use more descriptive variables here, like:
- `A` -> `self_X`
- `B` -> `other_X`
- `C` -> `joined_X`
- `m` -> `self_X_size`
- `n`-> `other_X_size`

2023-07-10 20:52 UTC, mbabadi commented on scvid/callbacks/distributed_pca.py
> +                    S_k = S_q[:k]
The same comment about working in q-dim space applies here ... let's discuss.

2023-07-10 20:52 UTC, mbabadi commented on scvid/callbacks/distributed_pca.py
> +    Distributed PCA.
... and the code is very compact and efficient!  you're crazy.

2023-07-10 20:55 UTC, mbabadi requested changes
You use PL like a magician! :)

2023-08-18 16:57 UTC, mbabadi approved these changes

2023-08-18 17:06 UTC, merged